csr-template-schema = {
  ? keyTypes: [ 1* $keyType ]
  ? subject: distinguishedName
  ? extensions: extensions
}

mandatory-wildcard = "**"
optional-wildcard = "*"
wildcard = mandatory-wildcard / optional-wildcard

; regtext matches all text strings but "*" and "**"
regtext = text .regexp "([^\*].*)|([\*][^\*].*)|([\*][\*].+)"

regtext-or-wildcard = regtext / wildcard

distinguishedName = {
  ? country: regtext-or-wildcard
  ? stateOrProvince: regtext-or-wildcard
  ? locality: regtext-or-wildcard
  ? organization: regtext-or-wildcard
  ? organizationalUnit: regtext-or-wildcard
  ? emailAddress: regtext-or-wildcard
  ? commonName: regtext-or-wildcard
}

$keyType /= rsaKeyType
$keyType /= ecKeyType

rsaKeyType = {
  PublicKeyType: "RSA"
  PublicKeyLength: $rsaKeySize
  SignatureType: $signatureType / mandatory-wildcard
}

$rsaKeySize /= 2048
$rsaKeySize /= 4096
$rsaKeySize /= 8192

$signatureType /= "sha256WithRSAEncryption"

ecKeyType = {
  PublicKeyType: "ecPublicKey"
  ? Curve: $ecCurve
  SignatureType: $ecSignatureType
}

$ecCurve /= "secp521r1"

$ecSignatureType /= "ecdsa-with-SHA256"
$ecSignatureType /= "Ed25519"

subjectaltname = {
  ? DNS: [ 1* regtext-or-wildcard ] ; TODO(tho) add checking wildcard to sec cons
  ? Email: [ 1* regtext ]
  ? URI: [ 1* regtext ]
  * $$subjectaltname-extension
  ; To extend this type to add an IP field, do:
  ; $$subjectaltname-extension //= (
  ;   ? IP: [ 1* regtext ]
  ; )
}

extensions = {
  ? keyUsage: [ 1* keyUsageType ]
  ? extendedKeyUsage: [ 1* extendedKeyUsageType ]
  subjectAltName: subjectaltname
}

keyUsageType /= "digitalSignature"
keyUsageType /= "nonRepudiation"
keyUsageType /= "keyEncipherment"
keyUsageType /= "dataEncipherment"
keyUsageType /= "keyAgreement"
keyUsageType /= "keyCertSign"
keyUsageType /= "cRLSign"
keyUsageType /= "encipherOnly"
keyUsageType /= "decipherOnly"

extendedKeyUsageType /= "serverAuth"
extendedKeyUsageType /= "clientAuth"
extendedKeyUsageType /= "codeSigning"
extendedKeyUsageType /= "emailProtection"
extendedKeyUsageType /= "timeStamping"
extendedKeyUsageType /= "OCSPSigning"

