; Tentative CDDL, should probably be enhanced to resolve
; the "cut" issue (RFC 8610, Sec. 3.5.4)
var_header = {
        K_KEY_PROVIDER => uint,
        K_KEY_ID => bstr,
        ? K_KEY_VERSION => uint,
        ? K_AUX_DATA => bstr,
        ? K_NONCE => bstr,
        ? K_AUTH_TAG => bstr,
        ? K_AAD => bstr,
        ? K_AAD_STRUCT => any,
        *uint => any ; extensions
}

K_RESERVED = 0
K_KEY_PROVIDER = 1
K_KEY_ID = 2
K_KEY_VERSION = 3
K_AUX_DATA = 4
K_NONCE = 5
K_AUTH_TAG = 6
K_AAD = 7
K_AAD_STRUCT = 8
        ; extend here
